# Generated by Django 4.2 on 2023-05-20 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('allocated_amount', models.IntegerField(default=0)),
                ('remaining_allocated_amount', models.IntegerField(default=0)),
                ('GRANT', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('allocated_amount', models.IntegerField(default=0)),
                ('remaining_allocated_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField()),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('description', models.TextField()),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.IntegerField(default=0)),
                ('remaining_budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING ', 'Pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'Rejected'), ('PAID', 'paid')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'cash'), ('BANK_TRANSFER', 'bank_transfer'), ('CHECK', 'check')], default='CASH', max_length=50)),
                ('date', models.DateTimeField()),
                ('note', models.CharField(max_length=1000, null=True)),
                ('files', models.FileField(upload_to=None)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.program')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('creation_date', models.DateTimeField(null=True)),
                ('role', models.CharField(choices=[('EMPLOYEE ', 'Employee'), ('SOCIAL WORK COMITTEE', 'Social Work Comittee')], default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALLOCATION', 'allocation'), ('PAYOUT', 'payout'), ('TRANSFER', 'tranfer'), ('INCOME', 'income')], max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'cash'), ('BANK_TRANSFER', 'bank_transfer'), ('CHECK', 'check')], max_length=50)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('recipe_name', models.CharField(max_length=50, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.article')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.fund')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.event')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter'),
        ),
    ]
