# Generated by Django 4.2 on 2023-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_article_chapter_alter_event_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SOCIAL WORK COMITTEE', 'Social Work Comittee')], default='EMPLOYEE', max_length=20),
        ),
    ]
