# Generated by Django 4.2 on 2023-06-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='allocated_amount',
        ),
    ]
