# Generated by Django 4.2 on 2023-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_chapter_section_socialwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialwork',
            name='title',
        ),
    ]
