# Generated by Django 4.2 on 2023-06-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_chapter_allocated_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='chapter',
        ),
        migrations.AddField(
            model_name='program',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Authentication.article'),
        ),
    ]
