# Generated by Django 4.2 on 2023-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_remove_socialwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
