# Generated by Django 4.2 on 2023-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_remove_program_chapter_program_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
