# Generated by Django 4.2 on 2023-06-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Authentication.article'),
        ),
    ]
