# Generated by Django 4.2 on 2023-05-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_chapter_current_balance_chapter_initial_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='The_Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INITIAL_BALANCE', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('CHAPTERS_INITIAL_BALANCE', models.IntegerField(default=0)),
                ('chapters_current_balance', models.IntegerField(default=0)),
                ('added_balance', models.IntegerField(default=0)),
                ('withdrawn_balance', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='section',
            old_name='grant',
            new_name='GRANT',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='initial_balance',
        ),
        migrations.AddField(
            model_name='chapter',
            name='added_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='withdrawn_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='INITIAL_BALANCE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.the_budget'),
        ),
    ]
