# Generated by Django 4.2 on 2023-05-07 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_the_budget_rename_grant_section_grant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_budget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
