# Generated by Django 4.2 on 2023-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_alter_the_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_budget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
