# Generated by Django 4.2 on 2023-05-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='budget',
        ),
    ]
