# Generated by Django 4.2 on 2023-05-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_remove_chapter_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwork',
            name='chapter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter'),
        ),
    ]
