# Generated by Django 4.2 on 2023-05-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_remove_the_budget_withdrawn_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='withdrawn_balance',
        ),
    ]
