# Generated by Django 4.2 on 2023-05-08 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_remove_chapter_withdrawn_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='INITIAL_BALANCE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='added_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialwork',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter'),
        ),
        migrations.AlterField(
            model_name='socialwork',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.section'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALLOCATION', 'allocation'), ('PAYOUT', 'payout')], max_length=10)),
                ('payment_method', models.CharField(choices=[('ESPECE', 'espece')], max_length=10)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.request')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
