# Generated by Django 4.2 on 2023-05-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0018_transaction_allocated_withdrawn_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_budget',
            name='chapters_current_balance',
        ),
    ]
