# Generated by Django 4.2 on 2023-05-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0019_remove_the_budget_chapters_current_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='socialwork',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='socialwork',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
