# Generated by Django 4.2 on 2023-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0020_rename_date_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'paid')], default='PENDING', max_length=10),
        ),
    ]
