# Generated by Django 4.2 on 2023-05-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0022_remove_event_location_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='added_balance',
        ),
    ]
