# Generated by Django 4.2 on 2023-05-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0023_remove_chapter_added_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
