# Generated by Django 4.2 on 2023-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0024_remove_user_city_remove_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Employee', max_length=50, null=True, unique=True, verbose_name='Name & Surname'),
        ),
    ]
