# Generated by Django 4.2 on 2023-05-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0025_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
