# Generated by Django 4.2 on 2023-05-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0028_alter_user_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
