# Generated by Django 4.2 on 2023-05-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0029_alter_user_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='the_budget',
            old_name='INITIAL_BALANCE',
            new_name='Allocated_Divisions_Amount',
        ),
        migrations.RemoveField(
            model_name='the_budget',
            name='CHAPTERS_INITIAL_BALANCE',
        ),
    ]
