# Generated by Django 4.2 on 2023-05-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0032_remove_the_budget_added_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_balance', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('recipe_name', models.CharField(max_length=50)),
            ],
        ),
    ]
