# Generated by Django 4.2 on 2023-05-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0034_rename_chapter_division_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Chapter',
        ),
        migrations.RenameField(
            model_name='socialwork',
            old_name='section',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='section',
            new_name='chapter',
        ),
    ]
