# Generated by Django 4.2 on 2023-05-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0035_rename_section_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='INITIAL_BALANCE',
            new_name='allocated_amount',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='current_balance',
            new_name='remaining_allocated_amount',
        ),
    ]
