# Generated by Django 4.2 on 2023-05-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0036_rename_initial_balance_division_allocated_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Move_fund',
            new_name='Move_income',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='INITIAL_BALANCE',
            new_name='allocated_amount',
        ),
    ]
