# Generated by Django 4.2 on 2023-05-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0038_rename_current_balance_chapter_remaining_allocated_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialWork',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='social_work',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING ', 'Pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'Rejected'), ('PAID', 'paid')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
