# Generated by Django 4.2 on 2023-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0039_rename_socialwork_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='allocated_withdrawn_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='division',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='withdrawn_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_allocated_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_income_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_withdrawn_payouts_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'cash'), ('BANK_TRANSFER', 'bank_transfer'), ('CHECK', 'check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('ALLOCATION', 'allocation'), ('PAYOUT', 'payout'), ('TRANSFER', 'tranfer'), ('INCOME', 'income')], max_length=10),
        ),
    ]
