# Generated by Django 4.2 on 2023-05-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0042_notification_delete_move_income'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='The_Budget',
            new_name='Fund',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
