# Generated by Django 4.2 on 2023-05-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0044_remove_transaction_total_allocated_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='Allocated_Divisions_Amount',
        ),
    ]
