# Generated by Django 4.2 on 2023-05-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0045_remove_fund_allocated_divisions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='date',
        ),
    ]
