# Generated by Django 4.2 on 2023-05-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0048_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('allocated_amount', models.IntegerField(default=0)),
                ('remaining_allocated_amount', models.IntegerField(default=0)),
                ('GRANT', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='GRANT',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='division',
        ),
        migrations.RemoveField(
            model_name='program',
            name='division',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='program',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter'),
        ),
        migrations.AddField(
            model_name='event',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.article'),
        ),
        migrations.AddField(
            model_name='program',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.article'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.article'),
        ),
    ]
