# Generated by Django 4.2 on 2023-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0049_article_remove_chapter_grant_remove_chapter_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'cash'), ('BANK_TRANSFER', 'bank_transfer'), ('CHECK', 'check')], default='CASH', max_length=50),
        ),
    ]
