# Generated by Django 4.2 on 2023-05-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0050_request_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='article',
        ),
        migrations.RemoveField(
            model_name='program',
            name='article',
        ),
        migrations.AddField(
            model_name='event',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chapter'),
        ),
    ]
